---
- hosts: 172.31.4.90
  become: yes
  tasks:
  - name: i want to install direct linux command
    command: hostname -f
    register: firsttaskresult


  - name: i want to display first task result
    debug: 
      msg: "{{firsttaskresult}}" 