---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:

  - name: i want install webserver on ubuntu Nodes
    apt:
     name: apache2
     state: present 
    when:  ansible_os_family=="Debian"

  - name: i want to restarted ubuntu nodes
    service:
        name: apache2
        state: restarted   
    when: ansible_os_family=="Debian"  

  - name: i want to install webserver on redhat nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"    

  - name: i want restart my httpd server
    service:
       naem: httpd
       state: restart
    when: ansible_os_family=="RedHat"   
       