---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver
    apt:
     name: apache2
     state: present 

  - name: i want to restarted
    service:
        name: apache2
        state: restarted   