---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:

  - name: i want install webserver on ubuntu Nodes
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present 
    when:  ansible_os_family=="Debian"

  - name: i want to restarted ubuntu nodes
    service:
        name: "{{mywebpackonubuntu}}"
        state: restarted   
    when: ansible_os_family=="Debian"  

  - name: i want to install webserver on redhat nodes
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"    
  - name: i want restart my httpd server
    service:
       name: "{{mywebpackonredhat}}"
       state: restarted
    when: ansible_os_family=="RedHat"   
       