---
# tasks file for mytomrole
- include_tasks: myaddusers.yml
- include_tasks: installjava.yml
- include_tasks: download.yml
- include_tasks: permissions.yml
- include_tasks: configuringAdminDB.yml
- include_tasks: mytomservice.yml
- include_tasks: mytomstart.yml
- include_tasks: deployjavaapp.yml

